#!/bin/bash

#install node and npm
sudo mkdir /usr/local/lib/nodejs
sudo tar -xJvf node-v10.15.1-linux-x64.tar.xz -C  /usr/local/lib/nodejs
sudo mv /usr/local/lib/nodejs/node-v10.15.1-linux-x64/ /usr/local/lib/nodejs/node-v10.15.1

echo " export NODEJS_HOME=/usr/local/lib/nodejs/node-v10.15.1/bin" >> ~/.profile
echo "export PATH=$NODEJS_HOME:$PATH" >> ~/.profile



. ~/.profile
node -v
npx -v
npm version
sudo ln -s /usr/local/lib/nodejs/node-$VERSION/bin/node /usr/bin/node
sudo ln -s /usr/local/lib/nodejs/node-$VERSION/bin/npm /usr/bin/npm
sudo ln -s /usr/local/lib/nodejs/node-$VERSION/bin/npx /usr/bin/npx



#install nvm
curl  https://raw.githubusercontent.com/creationix/nvm/master/install.sh  -o install0.sh
sudo chmod 755 install0.sh
./install0.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion





 nvm install 8.9.1
 nvm use 8.9.1
 npm init
 npm install -g npm-check
 npm install -g @angular/cli
 npm install -g @angular/cli@latest
 npm install -g typescript
 npm install angular --save
 npm install express --save
 npm link express 
npm install -g gulp



